### ISSUE TITLE
Calling postmap

### ISSUE THREAD

**Issue by Ulrar** [dhoppe/puppet-postfix#4]
Hi,

Might have missed something, but is there a way to call postmap on a file with this module ?
Seems to fit our needs except for managing the transport file which need to be postmap'ed.

I defined, in hiera, the config like this : 
```
postfix::config_file_hash:
  master.cf:
    config_file_path: '/etc/postfix/master.cf'
    config_file_source: 'puppet:///modules/postfix/master.cf'
  transport:
    config_file_path: '/etc/postfix/transport'
    config_file_source: 'puppet:///modules/postfix/transport'
```
Is there a way to define that transport should be postmap'ed ?
thanks !

PS : Sorry for the lot of edits but I really can't get used to github markdown.

**Comment by dhoppe** [comment]
Hi, 

unfortunately I did not implemented this feature in my module, but you should be able to override the ```config_file_notify``` parameter.

```
postfix::config_file_hash:
  master.cf:
    config_file_path: '/etc/postfix/master.cf'
    config_file_source: 'puppet:///modules/postfix/master.cf'
  transport:
    config_file_path: '/etc/postfix/transport'
    config_file_source: 'puppet:///modules/postfix/transport'
    config_file_notify: [ 'Exec[postmap]', 'Service[postfix]' ]
```

Of course you need to add the Exec resource somewhere and pass the filename to the **postmap** command. 

Kind regards, Dennis
